In [65]:
import pandas as pd
import numpy as np
import os

In [66]:
os.chdir('C:\\Users\\DELL\\Desktop\\Data Framing\\classification')

In [67]:
dataset_Train = pd.read_csv('Python_Module_Day_15.2_Credit_Risk_Train_data_XTRAIN.csv')
dataset_Test = pd.read_csv('Python_Module_Day_15.4_Credit_Risk_Validate_data_XTEST.csv')

In [68]:
Q1 = dataset_Train.quantile(0.25)
Q3 = dataset_Train.quantile(0.75)
IQR = Q3-Q1

dataset_Train = dataset_Train[~((dataset_Train<(Q1-1.5*IQR))
                       | (dataset_Train>(Q3+1.5*IQR))).any(axis=1)]

In [69]:
dataset_Train

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
10,LP001024,Male,Yes,2,Graduate,No,3200,700.0,70.0,360.0,1.0,Urban,Y
11,LP001027,Male,Yes,2,Graduate,NaN,2500,1840.0,109.0,360.0,1.0,Urban,Y
13,LP001029,Male,No,0,Graduate,No,1853,2840.0,114.0,360.0,1.0,Rural,N
15,LP001032,Male,No,0,Graduate,No,4950,0.0,125.0,360.0,1.0,Urban,Y
18,LP001038,Male,Yes,0,Not Graduate,No,4887,0.0,133.0,360.0,1.0,Rural,N
19,LP001041,Male,Yes,0,Graduate,NaN,2600,3500.0,115.0,NaN,1.0,Urban,Y
24,LP001052,Male,Yes,1,Graduate,NaN,3717,2925.0,151.0,360.0,NaN,Semiurban,N
25,LP001066,Male,Yes,0,Graduate,Yes,9560,0.0,191.0,360.0,1.0,Semiurban,Y
26,LP001068,Male,Yes,0,Graduate,No,2799,2253.0,122.0,360.0,1.0,Semiurban,Y
27,LP001073,Male,Yes,2,Not Graduate,No,4226,1040.0,110.0,360.0,1.0,Urban,Y
28,LP001086,Male,No,0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban,N
29,LP001087,Female,No,2,Graduate,NaN,3750,2083.0,120.0,360.0,1.0,Semiurban,Y
30,LP001091,Male,Yes,1,Graduate,NaN,4166,3369.0,201.0,360.0,NaN,Urban,N
31,LP001095,Male,No,0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban,N
32,LP001097,Male,No,1,Graduate,Yes,4692,0.0,106.0,360.0,1.0,Rural,N
33,LP001098,Male,Yes,0,Graduate,No,3500,1667.0,114.0,360.0,1.0,Semiurban,Y
35,LP001106,Male,Yes,0,Graduate,No,2275,2067.0,NaN,360.0,1.0,Urban,Y
37,LP001112,Female,Yes,0,Graduate,No,3667,1459.0,144.0,360.0,1.0,Semiurban,Y
39,LP001116,Male,No,0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban,Y
40,LP001119,Male,No,0,Graduate,No,3600,0.0,80.0,360.0,1.0,Urban,N
41,LP001120,Male,No,0,Graduate,No,1800,1213.0,47.0,360.0,1.0,Urban,Y
42,LP001123,Male,Yes,0,Graduate,No,2400,0.0,75.0,360.0,NaN,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,LP002807,Male,Yes,2,Not Graduate,No,3675,242.0,108.0,360.0,1.0,Semiurban,Y
562,LP002820,Male,Yes,0,Graduate,No,5923,2054.0,211.0,360.0,1.0,Rural,Y
563,LP002821,Male,No,0,Not Graduate,Yes,5800,0.0,132.0,360.0,1.0,Semiurban,Y
565,LP002833,Male,Yes,0,Not Graduate,No,4467,0.0,120.0,360.0,NaN,Rural,Y
566,LP002836,Male,No,0,Graduate,No,3333,0.0,70.0,360.0,1.0,Urban,Y
568,LP002840,Female,No,0,Graduate,No,2378,0.0,9.0,360.0,1.0,Urban,N
570,LP002842,Male,Yes,1,Graduate,No,3417,1750.0,186.0,360.0,1.0,Urban,Y
574,LP002863,Male,Yes,3+,Graduate,No,6406,0.0,150.0,360.0,1.0,Semiurban,N
577,LP002874,Male,No,0,Graduate,No,3229,2739.0,110.0,360.0,1.0,Urban,Y
578,LP002877,Male,Yes,1,Graduate,No,1782,2232.0,107.0,360.0,1.0,Rural,Y
579,LP002888,Male,No,0,Graduate,NaN,3182,2917.0,161.0,360.0,1.0,Urban,Y
580,LP002892,Male,Yes,2,Graduate,No,6540,0.0,205.0,360.0,1.0,Semiurban,Y
582,LP002894,Female,Yes,0,Graduate,No,3166,0.0,36.0,360.0,1.0,Semiurban,Y
583,LP002898,Male,Yes,1,Graduate,No,1880,0.0,61.0,360.0,NaN,Rural,N
586,LP002916,Male,Yes,0,Graduate,No,2297,1522.0,104.0,360.0,1.0,Urban,Y
587,LP002917,Female,No,0,Not Graduate,No,2165,0.0,70.0,360.0,1.0,Semiurban,Y
588,LP002925,NaN,No,0,Graduate,No,4750,0.0,94.0,360.0,1.0,Semiurban,Y
595,LP002940,Male,No,0,Not Graduate,No,3833,0.0,110.0,360.0,1.0,Rural,Y
596,LP002941,Male,Yes,2,Not Graduate,Yes,6383,1000.0,187.0,360.0,1.0,Rural,N
598,LP002945,Male,Yes,0,Graduate,Yes,9963,0.0,180.0,360.0,1.0,Rural,Y
599,LP002948,Male,Yes,2,Graduate,No,5780,0.0,192.0,360.0,1.0,Urban,Y
601,LP002950,Male,Yes,0,Not Graduate,NaN,2894,2792.0,155.0,360.0,1.0,Rural,Y
602,LP002953,Male,Yes,3+,Graduate,No,5703,0.0,128.0,360.0,1.0,Urban,Y
603,LP002958,Male,No,0,Graduate,No,3676,4301.0,172.0,360.0,1.0,Rural,Y
606,LP002961,Male,Yes,1,Graduate,No,3400,2500.0,173.0,360.0,1.0,Semiurban,Y
607,LP002964,Male,Yes,2,Not Graduate,No,3987,1411.0,157.0,360.0,1.0,Rural,Y
608,LP002974,Male,Yes,0,Graduate,No,3232,1950.0,108.0,360.0,1.0,Rural,Y
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y

In [70]:
dataset_Test

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,outcome
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,Y
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,Y
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,Y
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban,Y
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,N
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban,Y
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban,Y
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural,N
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban,Y
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban,Y
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.0,Urban,Y
11,LP001082,Male,Yes,1,Graduate,NaN,2185,1516,162.0,360.0,1.0,Semiurban,Y
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,NaN,Urban,Y
13,LP001094,Male,Yes,2,Graduate,NaN,12173,0,166.0,360.0,0.0,Semiurban,N
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.0,Semiurban,Y
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.0,Urban,Y
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.0,Urban,Y
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.0,Semiurban,Y
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.0,Urban,Y
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.0,Semiurban,Y
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.0,Urban,Y
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.0,Urban,Y
22,LP001128,NaN,No,0,Graduate,No,3909,0,101.0,360.0,1.0,Urban,Y
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.0,Urban,Y
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.0,Urban,Y
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.0,Rural,N
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,NaN,Urban,Y
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.0,Urban,Y
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,NaN,Semiurban,Y
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.0,Urban,Y
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.0,Rural,Y
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.0,Rural,N
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.0,Semiurban,Y
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.0,Rural,Y
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.0,Rural,N
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.0,Urban,Y
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.0,Rural,Y
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.0,Urban,Y
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.0,Rural,N
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.0,Urban,Y
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.0,Urban,Y
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.0,Rural,Y
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.0,Rural,Y
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,NaN,Rural,Y
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.0,Urban,Y
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.0,Rural,Y
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.0,Semiurban,Y
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.0,Urban,Y
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.0,Urban,Y
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.0,Urban,Y
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,NaN,Rural,Y
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.0,Semiurban,Y
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,NaN,Urban,Y
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.0,Semiurban,Y
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban,Y
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban,Y
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban,Y
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural,N
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural,Y

In [71]:
dataset_Train.isnull().sum()

Loan_ID               0
Gender                5
Married               1
Dependents            6
Education             0
Self_Employed        26
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           13
Loan_Amount_Term      8
Credit_History       39
Property_Area         0
Loan_Status           0
dtype: int64

In [72]:
dataset_Train["LoanAmount"].fillna(dataset_Train["LoanAmount"].mean(), inplace=True)
dataset_Train["Loan_Amount_Term"].fillna(dataset_Train["Loan_Amount_Term"].mean(), inplace=True)
dataset_Train["Credit_History"].fillna(dataset_Train["Credit_History"].mean(), inplace=True)

dataset_Train.groupby('Dependents').agg({'Dependents': np.size})
dataset_Train["Dependents"]=dataset_Train["Dependents"].fillna('0')
dataset_Train["Dependents"] = dataset_Train["Dependents"].astype('category')

dataset_Train.groupby('Gender').agg({'Gender': np.size})
dataset_Train["Gender"]=dataset_Train["Gender"].fillna('Male')
dataset_Train["Gender"] = dataset_Train["Gender"].astype('category')

dataset_Train.groupby('Married').agg({'Married': np.size})
dataset_Train["Married"]=dataset_Train["Married"].fillna('Yes')
dataset_Train["Married"] = dataset_Train["Married"].astype('category')

dataset_Train.groupby('Self_Employed').agg({'Self_Employed': np.size})
dataset_Train["Self_Employed"]=dataset_Train["Self_Employed"].fillna('No')
dataset_Train["Self_Employed"] = dataset_Train["Self_Employed"].astype('category')

dataset_Train = pd.get_dummies(dataset_Train, columns=['Dependents'], drop_first=True)
dataset_Train = pd.get_dummies(dataset_Train, columns=['Gender'], drop_first=True)
dataset_Train = pd.get_dummies(dataset_Train, columns=['Married'], drop_first=True)
dataset_Train = pd.get_dummies(dataset_Train, columns=['Property_Area'], drop_first=True)

dataset_Train = pd.get_dummies(dataset_Train, columns=['Education'], drop_first=True)
dataset_Train = pd.get_dummies(dataset_Train, columns=['Self_Employed'], drop_first=True)
dataset_Train = pd.get_dummies(dataset_Train, columns=['Loan_Status'], drop_first=True)

In [73]:
dataset_Train

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Dependents_1,Dependents_2,Dependents_3+,Gender_Male,Married_Yes,Property_Area_Semiurban,Property_Area_Urban,Education_Not Graduate,Self_Employed_Yes,Loan_Status_Y
0,LP001002,5849,0.0,129.205195,360.0,1.0,0,0,0,1,0,0,1,0,0,1
1,LP001003,4583,1508.0,128.000000,360.0,1.0,1,0,0,1,1,0,0,0,0,0
2,LP001005,3000,0.0,66.000000,360.0,1.0,0,0,0,1,1,0,1,0,1,1
3,LP001006,2583,2358.0,120.000000,360.0,1.0,0,0,0,1,1,0,1,1,0,1
4,LP001008,6000,0.0,141.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
5,LP001011,5417,4196.0,267.000000,360.0,1.0,0,1,0,1,1,0,1,0,1,1
6,LP001013,2333,1516.0,95.000000,360.0,1.0,0,0,0,1,1,0,1,1,0,1
8,LP001018,4006,1526.0,168.000000,360.0,1.0,0,1,0,1,1,0,1,0,0,1
10,LP001024,3200,700.0,70.000000,360.0,1.0,0,1,0,1,1,0,1,0,0,1
11,LP001027,2500,1840.0,109.000000,360.0,1.0,0,1,0,1,1,0,1,0,0,1
13,LP001029,1853,2840.0,114.000000,360.0,1.0,0,0,0,1,0,0,0,0,0,0
15,LP001032,4950,0.0,125.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
18,LP001038,4887,0.0,133.000000,360.0,1.0,0,0,0,1,1,0,0,1,0,0
19,LP001041,2600,3500.0,115.000000,360.0,1.0,0,0,0,1,1,0,1,0,0,1
24,LP001052,3717,2925.0,151.000000,360.0,1.0,1,0,0,1,1,1,0,0,0,0
25,LP001066,9560,0.0,191.000000,360.0,1.0,0,0,0,1,1,1,0,0,1,1
26,LP001068,2799,2253.0,122.000000,360.0,1.0,0,0,0,1,1,1,0,0,0,1
27,LP001073,4226,1040.0,110.000000,360.0,1.0,0,1,0,1,1,0,1,1,0,1
28,LP001086,1442,0.0,35.000000,360.0,1.0,0,0,0,1,0,0,1,1,0,0
29,LP001087,3750,2083.0,120.000000,360.0,1.0,0,1,0,0,0,1,0,0,0,1
30,LP001091,4166,3369.0,201.000000,360.0,1.0,1,0,0,1,1,0,1,0,0,0
31,LP001095,3167,0.0,74.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,0
32,LP001097,4692,0.0,106.000000,360.0,1.0,1,0,0,1,0,0,0,0,1,0
33,LP001098,3500,1667.0,114.000000,360.0,1.0,0,0,0,1,1,1,0,0,0,1
35,LP001106,2275,2067.0,129.205195,360.0,1.0,0,0,0,1,1,0,1,0,0,1
37,LP001112,3667,1459.0,144.000000,360.0,1.0,0,0,0,0,1,1,0,0,0,1
39,LP001116,3748,1668.0,110.000000,360.0,1.0,0,0,0,1,0,1,0,1,0,1
40,LP001119,3600,0.0,80.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,0
41,LP001120,1800,1213.0,47.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
42,LP001123,2400,0.0,75.000000,360.0,1.0,0,0,0,1,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
560,LP002807,3675,242.0,108.000000,360.0,1.0,0,1,0,1,1,1,0,1,0,1
562,LP002820,5923,2054.0,211.000000,360.0,1.0,0,0,0,1,1,0,0,0,0,1
563,LP002821,5800,0.0,132.000000,360.0,1.0,0,0,0,1,0,1,0,1,1,1
565,LP002833,4467,0.0,120.000000,360.0,1.0,0,0,0,1,1,0,0,1,0,1
566,LP002836,3333,0.0,70.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
568,LP002840,2378,0.0,9.000000,360.0,1.0,0,0,0,0,0,0,1,0,0,0
570,LP002842,3417,1750.0,186.000000,360.0,1.0,1,0,0,1,1,0,1,0,0,1
574,LP002863,6406,0.0,150.000000,360.0,1.0,0,0,1,1,1,1,0,0,0,0
577,LP002874,3229,2739.0,110.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
578,LP002877,1782,2232.0,107.000000,360.0,1.0,1,0,0,1,1,0,0,0,0,1
579,LP002888,3182,2917.0,161.000000,360.0,1.0,0,0,0,1,0,0,1,0,0,1
580,LP002892,6540,0.0,205.000000,360.0,1.0,0,1,0,1,1,1,0,0,0,1
582,LP002894,3166,0.0,36.000000,360.0,1.0,0,0,0,0,1,1,0,0,0,1
583,LP002898,1880,0.0,61.000000,360.0,1.0,1,0,0,1,1,0,0,0,0,0
586,LP002916,2297,1522.0,104.000000,360.0,1.0,0,0,0,1,1,0,1,0,0,1
587,LP002917,2165,0.0,70.000000,360.0,1.0,0,0,0,0,0,1,0,1,0,1
588,LP002925,4750,0.0,94.000000,360.0,1.0,0,0,0,1,0,1,0,0,0,1
595,LP002940,3833,0.0,110.000000,360.0,1.0,0,0,0,1,0,0,0,1,0,1
596,LP002941,6383,1000.0,187.000000,360.0,1.0,0,1,0,1,1,0,0,1,1,0
598,LP002945,9963,0.0,180.000000,360.0,1.0,0,0,0,1,1,0,0,0,1,1
599,LP002948,5780,0.0,192.000000,360.0,1.0,0,1,0,1,1,0,1,0,0,1
601,LP002950,2894,2792.0,155.000000,360.0,1.0,0,0,0,1,1,0,0,1,0,1
602,LP002953,5703,0.0,128.000000,360.0,1.0,0,0,1,1,1,0,1,0,0,1
603,LP002958,3676,4301.0,172.000000,360.0,1.0,0,0,0,1,0,0,0,0,0,1
606,LP002961,3400,2500.0,173.000000,360.0,1.0,1,0,0,1,1,1,0,0,0,1
607,LP002964,3987,1411.0,157.000000,360.0,1.0,0,1,0,1,1,0,0,1,0,1
608,LP002974,3232,1950.0,108.000000,360.0,1.0,0,0,0,1,1,0,0,0,0,1
609,LP002978,2900,0.0,71.000000,360.0,1.0,0,0,0,0,0,0,0,0,0,1
611,LP002983,8072,240.0,253.000000,360.0,1.0,1,0,0,1,1,0,1,0,0,1
612,LP002984,7583,0.0,187.000000,360.0,1.0,0,1,0,1,1,0,1,0,0,1

In [74]:
dataset_Train_d=dataset_Train.drop(['Loan_ID'], axis=1)

In [75]:
x_train = dataset_Train_d.iloc[:,:-1].values
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,5849.0,0.0,129.205195,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1,4583.0,1508.0,128.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
2,3000.0,0.0,66.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
3,2583.0,2358.0,120.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
4,6000.0,0.0,141.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5,5417.0,4196.0,267.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
6,2333.0,1516.0,95.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
7,4006.0,1526.0,168.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
8,3200.0,700.0,70.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
9,2500.0,1840.0,109.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
10,1853.0,2840.0,114.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
11,4950.0,0.0,125.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
12,4887.0,0.0,133.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
13,2600.0,3500.0,115.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
14,3717.0,2925.0,151.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
15,9560.0,0.0,191.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
16,2799.0,2253.0,122.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
17,4226.0,1040.0,110.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
18,1442.0,0.0,35.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
19,3750.0,2083.0,120.000000,360.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
20,4166.0,3369.0,201.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
21,3167.0,0.0,74.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
22,4692.0,0.0,106.000000,360.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
23,3500.0,1667.0,114.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
24,2275.0,2067.0,129.205195,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
25,3667.0,1459.0,144.000000,360.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
26,3748.0,1668.0,110.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
27,3600.0,0.0,80.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
28,1800.0,1213.0,47.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
29,2400.0,0.0,75.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
368,3675.0,242.0,108.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0
369,5923.0,2054.0,211.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
370,5800.0,0.0,132.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0
371,4467.0,0.0,120.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
372,3333.0,0.0,70.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
373,2378.0,0.0,9.000000,360.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
374,3417.0,1750.0,186.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
375,6406.0,0.0,150.000000,360.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
376,3229.0,2739.0,110.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
377,1782.0,2232.0,107.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
378,3182.0,2917.0,161.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
379,6540.0,0.0,205.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
380,3166.0,0.0,36.000000,360.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
381,1880.0,0.0,61.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
382,2297.0,1522.0,104.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
383,2165.0,0.0,70.000000,360.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
384,4750.0,0.0,94.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
385,3833.0,0.0,110.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
386,6383.0,1000.0,187.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0
387,9963.0,0.0,180.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
388,5780.0,0.0,192.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
389,2894.0,2792.0,155.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
390,5703.0,0.0,128.000000,360.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
391,3676.0,4301.0,172.000000,360.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
392,3400.0,2500.0,173.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
393,3987.0,1411.0,157.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
394,3232.0,1950.0,108.000000,360.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
395,2900.0,0.0,71.000000,360.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
396,8072.0,240.0,253.000000,360.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
397,7583.0,0.0,187.000000,360.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [76]:
y_train = dataset_Train_d.iloc[:,-1:].values
y_train

array([[1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]], dtype=uint8)

In [77]:
#Test DataSet

In [78]:
dataset_Test.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
outcome               0
dtype: int64

In [79]:
dataset_Test

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,outcome
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban,Y
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban,Y
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban,Y
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban,Y
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban,N
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban,Y
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban,Y
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural,N
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban,Y
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban,Y
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.0,Urban,Y
11,LP001082,Male,Yes,1,Graduate,NaN,2185,1516,162.0,360.0,1.0,Semiurban,Y
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,NaN,Urban,Y
13,LP001094,Male,Yes,2,Graduate,NaN,12173,0,166.0,360.0,0.0,Semiurban,N
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.0,Semiurban,Y
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.0,Urban,Y
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.0,Urban,Y
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.0,Semiurban,Y
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.0,Urban,Y
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.0,Semiurban,Y
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.0,Urban,Y
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.0,Urban,Y
22,LP001128,NaN,No,0,Graduate,No,3909,0,101.0,360.0,1.0,Urban,Y
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.0,Urban,Y
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.0,Urban,Y
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.0,Rural,N
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,NaN,Urban,Y
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.0,Urban,Y
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,NaN,Semiurban,Y
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.0,Urban,Y
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.0,Rural,Y
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.0,Rural,N
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.0,Semiurban,Y
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.0,Rural,Y
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.0,Rural,N
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.0,Urban,Y
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.0,Rural,Y
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.0,Urban,Y
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.0,Rural,N
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.0,Urban,Y
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.0,Urban,Y
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.0,Rural,Y
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.0,Rural,Y
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,NaN,Rural,Y
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.0,Urban,Y
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.0,Rural,Y
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.0,Semiurban,Y
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.0,Urban,Y
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.0,Urban,Y
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.0,Urban,Y
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,NaN,Rural,Y
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.0,Semiurban,Y
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,NaN,Urban,Y
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.0,Semiurban,Y
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban,Y
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban,Y
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban,Y
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural,N
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural,Y

In [80]:
dataset_Test["LoanAmount"].fillna(dataset_Test["LoanAmount"].mean(), inplace=True)
dataset_Test["Loan_Amount_Term"].fillna(dataset_Test["Loan_Amount_Term"].mean(), inplace=True)
dataset_Test["Credit_History"].fillna(dataset_Test["Credit_History"].mean(), inplace=True)

dataset_Test.groupby('Dependents').agg({'Dependents': np.size})
dataset_Test["Dependents"]=dataset_Test["Dependents"].fillna('0')
dataset_Test["Dependents"] = dataset_Test["Dependents"].astype('category')

dataset_Test.groupby('Gender').agg({'Gender': np.size})
dataset_Test["Gender"]=dataset_Test["Gender"].fillna('Male')
dataset_Test["Gender"] = dataset_Test["Gender"].astype('category')

dataset_Test.groupby('Married').agg({'Married': np.size})
dataset_Test["Married"]=dataset_Test["Married"].fillna('Yes')
dataset_Test["Married"] = dataset_Test["Married"].astype('category')

dataset_Test.groupby('Self_Employed').agg({'Self_Employed': np.size})
dataset_Test["Self_Employed"]=dataset_Test["Self_Employed"].fillna('No')
dataset_Test["Self_Employed"] = dataset_Test["Self_Employed"].astype('category')

In [81]:
dataset_Test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
outcome              0
dtype: int64

In [82]:
dataset_Test = pd.get_dummies(dataset_Test, columns=['Dependents'], drop_first=True)
dataset_Test = pd.get_dummies(dataset_Test, columns=['Gender'], drop_first=True)
dataset_Test = pd.get_dummies(dataset_Test, columns=['Married'], drop_first=True)
dataset_Test = pd.get_dummies(dataset_Test, columns=['Property_Area'], drop_first=True)
dataset_Test = pd.get_dummies(dataset_Test, columns=['Education'], drop_first=True)
dataset_Test = pd.get_dummies(dataset_Test, columns=['Self_Employed'], drop_first=True)

In [83]:
dataset_Test_d = pd.get_dummies(dataset_Test, columns=['outcome'], drop_first=True)

In [84]:
dataset_Test_d=dataset_Test_d.drop(['Loan_ID'], axis=1)

In [85]:
dataset_Test_d

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Dependents_1,Dependents_2,Dependents_3+,Gender_Male,Married_Yes,Property_Area_Semiurban,Property_Area_Urban,Education_Not Graduate,Self_Employed_Yes,outcome_Y
0,5720,0,110.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
1,3076,1500,126.0,360.0,1.000000,1,0,0,1,1,0,1,0,0,1
2,5000,1800,208.0,360.0,1.000000,0,1,0,1,1,0,1,0,0,1
3,2340,2546,100.0,360.0,0.825444,0,1,0,1,1,0,1,0,0,1
4,3276,0,78.0,360.0,1.000000,0,0,0,1,0,0,1,1,0,0
5,2165,3422,152.0,360.0,1.000000,0,0,0,1,1,0,1,1,1,1
6,2226,0,59.0,360.0,1.000000,1,0,0,0,0,1,0,1,0,1
7,3881,0,147.0,360.0,0.000000,0,1,0,1,1,0,0,1,0,0
8,13633,0,280.0,240.0,1.000000,0,1,0,1,1,0,1,0,0,1
9,2400,2400,123.0,360.0,1.000000,0,0,0,1,0,1,0,1,0,1
10,3091,0,90.0,360.0,1.000000,0,0,0,1,0,0,1,1,0,1
11,2185,1516,162.0,360.0,1.000000,1,0,0,1,1,1,0,0,0,1
12,4166,0,40.0,180.0,0.825444,0,0,1,1,0,0,1,0,0,1
13,12173,0,166.0,360.0,0.000000,0,1,0,1,1,1,0,0,0,0
14,4666,0,124.0,360.0,1.000000,0,0,0,0,0,1,0,0,0,1
15,5667,0,131.0,360.0,1.000000,1,0,0,1,0,0,1,0,0,1
16,4583,2916,200.0,360.0,1.000000,0,1,0,1,1,0,1,0,0,1
17,3786,333,126.0,360.0,1.000000,0,0,1,1,1,1,0,0,0,1
18,9226,7916,300.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
19,1300,3470,100.0,180.0,1.000000,0,0,0,1,0,1,0,0,0,1
20,1888,1620,48.0,360.0,1.000000,1,0,0,1,1,0,1,1,0,1
21,2083,0,28.0,180.0,1.000000,0,0,1,0,0,0,1,1,0,1
22,3909,0,101.0,360.0,1.000000,0,0,0,1,0,0,1,0,0,1
23,3765,0,125.0,360.0,1.000000,0,0,0,0,0,0,1,1,0,1
24,5400,4380,290.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
25,0,24000,148.0,360.0,0.000000,0,0,0,1,0,0,0,0,0,0
26,4363,1250,140.0,360.0,0.825444,0,1,0,1,1,0,1,0,0,1
27,7500,3750,275.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
28,3772,833,57.0,360.0,0.825444,0,0,0,1,1,1,0,0,0,1
29,2942,2382,125.0,180.0,1.000000,0,0,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,2292,1558,119.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
338,2360,3355,87.0,240.0,1.000000,1,0,0,1,1,0,0,0,1,1
339,4333,2333,162.0,360.0,0.000000,0,0,0,0,0,0,0,0,0,0
340,2623,4831,122.0,180.0,1.000000,0,0,0,1,1,1,0,0,1,1
341,3972,4275,187.0,360.0,1.000000,0,0,0,1,0,0,0,0,1,1
342,3522,0,81.0,180.0,1.000000,0,0,1,1,1,0,0,1,0,0
343,4700,0,80.0,360.0,1.000000,1,0,0,1,1,0,1,0,0,1
344,6858,0,176.0,360.0,1.000000,0,0,0,1,0,0,0,0,0,1
345,8334,0,260.0,360.0,1.000000,0,0,1,1,1,0,1,0,0,1
346,3391,1966,133.0,360.0,0.000000,0,0,0,1,1,0,0,0,0,0
347,2868,0,70.0,360.0,1.000000,0,0,0,1,0,0,1,1,0,1
348,3418,1380,135.0,360.0,1.000000,0,1,0,1,1,0,1,1,0,1
349,2500,296,137.0,300.0,1.000000,0,0,0,1,1,0,0,0,1,1
350,8667,0,254.0,360.0,1.000000,0,1,0,1,1,0,0,0,0,1
351,2283,15000,106.0,360.0,0.825444,0,0,0,1,0,0,0,0,0,1
352,5817,910,109.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
353,5119,3769,120.0,360.0,1.000000,0,0,0,1,1,0,0,0,0,1
354,5316,187,158.0,180.0,0.000000,0,0,1,1,1,1,0,1,0,1
355,7603,1213,197.0,360.0,1.000000,0,0,1,1,1,0,1,0,0,1
356,3791,1936,85.0,360.0,1.000000,1,0,0,1,1,0,1,0,0,1
357,2500,0,60.0,360.0,1.000000,0,0,0,1,0,0,1,0,0,1
358,3132,0,76.0,360.0,0.825444,0,1,0,1,1,0,0,1,0,1
359,4000,2667,152.0,360.0,1.000000,0,0,0,1,0,1,0,0,0,1
360,8550,4255,96.0,360.0,0.825444,0,0,0,0,1,0,1,0,0,1
361,2269,2167,99.0,360.0,1.000000,1,0,0,1,1,1,0,0,0,1
362,4009,1777,113.0,360.0,1.000000,0,0,1,1,1,0,1,1,1,1
363,4158,709,115.0,360.0,1.000000,0,0,0,1,1,0,1,0,0,1
364,3250,1993,126.0,360.0,0.825444,0,0,0,1,0,1,0,0,0,1
365,5000,2393,158.0,360.0,1.000000,0,0,0,1,1,0,0,0,0,0
366,9200,0,98.0,180.0,1.000000,0,0,0,1,0,0,0,0,1,1

In [86]:
x_test = dataset_Test_d.iloc[:,:-1].values
pd.DataFrame(x_test)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,5720.0,0.0,110.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,3076.0,1500.0,126.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
2,5000.0,1800.0,208.0,360.0,1.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
3,2340.0,2546.0,100.0,360.0,0.825444,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
4,3276.0,0.0,78.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
5,2165.0,3422.0,152.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
6,2226.0,0.0,59.0,360.0,1.000000,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
7,3881.0,0.0,147.0,360.0,0.000000,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
8,13633.0,0.0,280.0,240.0,1.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
9,2400.0,2400.0,123.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
10,3091.0,0.0,90.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
11,2185.0,1516.0,162.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
12,4166.0,0.0,40.0,180.0,0.825444,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
13,12173.0,0.0,166.0,360.0,0.000000,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
14,4666.0,0.0,124.0,360.0,1.000000,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
15,5667.0,0.0,131.0,360.0,1.000000,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
16,4583.0,2916.0,200.0,360.0,1.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
17,3786.0,333.0,126.0,360.0,1.000000,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
18,9226.0,7916.0,300.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
19,1300.0,3470.0,100.0,180.0,1.000000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
20,1888.0,1620.0,48.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
21,2083.0,0.0,28.0,180.0,1.000000,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
22,3909.0,0.0,101.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
23,3765.0,0.0,125.0,360.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
24,5400.0,4380.0,290.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
25,0.0,24000.0,148.0,360.0,0.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
26,4363.0,1250.0,140.0,360.0,0.825444,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
27,7500.0,3750.0,275.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
28,3772.0,833.0,57.0,360.0,0.825444,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
29,2942.0,2382.0,125.0,180.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,2292.0,1558.0,119.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
338,2360.0,3355.0,87.0,240.0,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
339,4333.0,2333.0,162.0,360.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
340,2623.0,4831.0,122.0,180.0,1.000000,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0
341,3972.0,4275.0,187.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
342,3522.0,0.0,81.0,180.0,1.000000,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0
343,4700.0,0.0,80.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
344,6858.0,0.0,176.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
345,8334.0,0.0,260.0,360.0,1.000000,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
346,3391.0,1966.0,133.0,360.0,0.000000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
347,2868.0,0.0,70.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
348,3418.0,1380.0,135.0,360.0,1.000000,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0
349,2500.0,296.0,137.0,300.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
350,8667.0,0.0,254.0,360.0,1.000000,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
351,2283.0,15000.0,106.0,360.0,0.825444,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
352,5817.0,910.0,109.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
353,5119.0,3769.0,120.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
354,5316.0,187.0,158.0,180.0,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
355,7603.0,1213.0,197.0,360.0,1.000000,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
356,3791.0,1936.0,85.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
357,2500.0,0.0,60.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
358,3132.0,0.0,76.0,360.0,0.825444,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
359,4000.0,2667.0,152.0,360.0,1.000000,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
360,8550.0,4255.0,96.0,360.0,0.825444,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
361,2269.0,2167.0,99.0,360.0,1.000000,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0
362,4009.0,1777.0,113.0,360.0,1.000000,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0
363,4158.0,709.0,115.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
364,3250.0,1993.0,126.0,360.0,0.825444,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
365,5000.0,2393.0,158.0,360.0,1.000000,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0
366,9200.0,0.0,98.0,180.0,1.000000,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0

In [87]:
y_test = dataset_Test_d.iloc[:,-1:].values
pd.DataFrame(y_test)

     0
0    1
1    1
2    1
3    1
4    0
5    1
6    1
7    0
8    1
9    1
10   1
11   1
12   1
13   0
14   1
15   1
16   1
17   1
18   1
19   1
20   1
21   1
22   1
23   1
24   1
25   0
26   1
27   1
28   1
29   1
..  ..
337  1
338  1
339  0
340  1
341  1
342  0
343  1
344  1
345  1
346  0
347  1
348  1
349  1
350  1
351  1
352  1
353  1
354  1
355  1
356  1
357  1
358  1
359  1
360  1
361  1
362  1
363  1
364  1
365  0
366  1

[367 rows x 1 columns]

In [88]:
from sklearn.preprocessing import StandardScaler
sc_x_test = StandardScaler()
x_test = sc_x_test.fit_transform(x_test)

In [89]:
pd.DataFrame(x_test)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.186461,-0.673335,-0.429368,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
1,-0.352692,-0.029848,-0.166482,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
2,0.039641,0.098849,1.180807,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
3,-0.502774,0.418877,-0.593671,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
4,-0.311909,-0.673335,-0.955139,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
5,-0.538459,0.794673,0.260707,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,2.986456
6,-0.526020,-0.673335,-1.267316,0.270603,0.479180,2.308156,-0.437674,-0.349749,-2.059820,-1.318638,1.470984,-0.785328,1.835497,-0.334845
7,-0.188540,-0.673335,0.178555,0.270603,-2.265952,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
8,1.800044,-0.673335,2.363793,-1.588932,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
9,-0.490539,0.356244,-0.215773,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,1.835497,-0.334845
10,-0.349634,-0.673335,-0.757975,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
11,-0.534381,-0.022984,0.425011,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
12,-0.130424,-0.673335,-1.579493,-2.518700,0.000000,-0.433246,-0.437674,2.859196,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
13,1.502328,-0.673335,0.490732,0.270603,-2.265952,-0.433246,2.284806,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
14,-0.028467,-0.673335,-0.199343,0.270603,0.479180,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
15,0.175653,-0.673335,-0.084330,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
16,-0.045391,0.577603,1.049364,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
17,-0.207912,-0.530481,-0.166482,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
18,0.901388,2.722560,2.692400,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
19,-0.714846,0.815265,-0.593671,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
20,-0.594944,0.021631,-1.448050,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,-0.334845
21,-0.555180,-0.673335,-1.776657,-2.518700,0.479180,-0.433246,-0.437674,2.859196,-2.059820,-1.318638,-0.679817,1.273353,1.835497,-0.334845
22,-0.182831,-0.673335,-0.577241,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
23,-0.212194,-0.673335,-0.182913,0.270603,0.479180,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,-0.679817,1.273353,1.835497,-0.334845
24,0.121208,1.205647,2.528096,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
25,-0.979937,9.622455,0.194986,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
26,-0.090253,-0.137096,0.063543,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
27,0.549430,0.935382,2.281641,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
28,-0.210767,-0.315985,-1.300177,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
29,-0.380017,0.348522,-0.182913,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,-0.512562,-0.004967,-0.281495,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
338,-0.498696,0.765931,-0.807266,-1.588932,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,2.986456
339,-0.096370,0.327502,0.425011,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
340,-0.445066,1.399122,-0.232204,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,2.986456
341,-0.169984,1.160603,0.835770,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,2.986456
342,-0.261746,-0.673335,-0.905848,-2.518700,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
343,-0.021533,-0.673335,-0.922279,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
344,0.418516,-0.673335,0.655036,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
345,0.719496,-0.673335,2.035186,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
346,-0.288459,0.170062,-0.051470,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
347,-0.395107,-0.673335,-1.086582,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
348,-0.282953,-0.081327,-0.018609,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,-0.334845
349,-0.470148,-0.546354,0.014252,-0.659165,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,2.986456
350,0.787400,-0.673335,1.936604,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
351,-0.514397,5.761534,-0.495089,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
352,0.206240,-0.282953,-0.445798,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
353,0.063907,0.943533,-0.265064,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
354,0.104079,-0.593114,0.359289,-2.518700,-2.265952,-0.433246,-0.437674,2.859196,0.485479,0.758358,1.470984,-0.785328,1.835497,-0.334845
355,0.570434,-0.152969,1.000073,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
356,-0.206893,0.157192,-0.840127,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
357,-0.470148,-0.673335,-1.250886,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
358,-0.341273,-0.673335,-0.988000,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
359,-0.164274,0.470785,0.260707,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
360,0.763542,1.152023,-0.659393,0.270603,0.000000,-0.433246,-0.437674,-0.349749,-2.059820,0.758358,-0.679817,1.273353,-0.544812,-0.334845
361,-0.517252,0.256289,-0.610102,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
362,-0.162439,0.088982,-0.380077,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,1.835497,2.986456
363,-0.132056,-0.369180,-0.347216,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
364,-0.317211,0.181644,-0.166482,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
365,0.039641,0.353241,0.359289,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
366,0.896087,-0.673335,-0.626532,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,2.986456

In [90]:
dataset_New_Pred = pd.read_csv('Python_Module_Day_15.3_Credit_Risk_Test_data.csv')

In [91]:
dataset_New_Pred

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.0,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.0,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.0,Rural
8,LP001059,Male,Yes,2,Graduate,NaN,13633,0,280.0,240.0,1.0,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.0,Semiurban
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.0,Urban
11,LP001082,Male,Yes,1,Graduate,NaN,2185,1516,162.0,360.0,1.0,Semiurban
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,NaN,Urban
13,LP001094,Male,Yes,2,Graduate,NaN,12173,0,166.0,360.0,0.0,Semiurban
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.0,Semiurban
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.0,Urban
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.0,Urban
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.0,Semiurban
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.0,Urban
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.0,Semiurban
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.0,Urban
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.0,Urban
22,LP001128,NaN,No,0,Graduate,No,3909,0,101.0,360.0,1.0,Urban
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.0,Urban
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.0,Urban
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.0,Rural
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,NaN,Urban
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.0,Urban
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,NaN,Semiurban
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.0,Urban
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.0,Rural
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.0,Rural
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.0,Semiurban
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.0,Rural
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.0,Rural
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.0,Urban
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.0,Rural
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.0,Urban
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.0,Rural
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.0,Urban
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.0,Urban
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.0,Rural
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.0,Rural
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,NaN,Rural
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.0,Urban
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.0,Rural
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.0,Semiurban
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.0,Urban
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.0,Urban
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.0,Urban
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,NaN,Rural
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.0,Semiurban
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,NaN,Urban
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.0,Semiurban
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

In [92]:
dataset_New_Pred.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [93]:
dataset_New_Pred["LoanAmount"].fillna(dataset_New_Pred["LoanAmount"].mean(), inplace=True)
dataset_New_Pred["Loan_Amount_Term"].fillna(dataset_New_Pred["Loan_Amount_Term"].mean(), inplace=True)
dataset_New_Pred["Credit_History"].fillna(dataset_New_Pred["Credit_History"].mean(), inplace=True)

dataset_New_Pred.groupby('Dependents').agg({'Dependents': np.size})
dataset_New_Pred["Dependents"]=dataset_New_Pred["Dependents"].fillna('0')
dataset_New_Pred["Dependents"] = dataset_New_Pred["Dependents"].astype('category')

dataset_New_Pred.groupby('Gender').agg({'Gender': np.size})
dataset_New_Pred["Gender"]=dataset_New_Pred["Gender"].fillna('Male')
dataset_New_Pred["Gender"] = dataset_New_Pred["Gender"].astype('category')

dataset_New_Pred.groupby('Self_Employed').agg({'Self_Employed': np.size})
dataset_New_Pred["Self_Employed"]=dataset_New_Pred["Self_Employed"].fillna('No')
dataset_New_Pred["Self_Employed"] = dataset_New_Pred["Self_Employed"].astype('category')

In [94]:
dataset_New_Pred_d = dataset_New_Pred.drop(['Loan_ID'], axis=1)

In [95]:
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Dependents'], drop_first=True)
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Gender'], drop_first=True)
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Married'], drop_first=True)
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Property_Area'], drop_first=True)
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Education'], drop_first=True)
dataset_New_Pred_d = pd.get_dummies(dataset_New_Pred_d, columns=['Self_Employed'], drop_first=True)

In [96]:
len(dataset_New_Pred_d)

367

In [97]:
dataset_New_Pred.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [98]:
x_new= dataset_New_Pred_d.iloc[:,:].values
x_new

array([[5.720e+03, 0.000e+00, 1.100e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [3.076e+03, 1.500e+03, 1.260e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       [5.000e+03, 1.800e+03, 2.080e+02, ..., 1.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [3.250e+03, 1.993e+03, 1.260e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [5.000e+03, 2.393e+03, 1.580e+02, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [9.200e+03, 0.000e+00, 9.800e+01, ..., 0.000e+00, 0.000e+00,
        1.000e+00]])

In [99]:
sc_x_new= StandardScaler()
x_new = sc_x_new.fit_transform(x_new)

In [100]:
x_new

array([[ 0.1864605 , -0.67333511, -0.42936789, ...,  1.27335328,
        -0.5448117 , -0.33484506],
       [-0.35269225, -0.02984821, -0.16648218, ...,  1.27335328,
        -0.5448117 , -0.33484506],
       [ 0.0396413 ,  0.09884917,  1.18080709, ...,  1.27335328,
        -0.5448117 , -0.33484506],
       ...,
       [-0.31721094,  0.18164449, -0.16648218, ..., -0.78532801,
        -0.5448117 , -0.33484506],
       [ 0.0396413 ,  0.353241  ,  0.35928924, ..., -0.78532801,
        -0.5448117 , -0.33484506],
       [ 0.89608667, -0.67333511, -0.62653217, ..., -0.78532801,
        -0.5448117 ,  2.98645591]])

In [101]:
pd.DataFrame(x_new)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.186461,-0.673335,-0.429368,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
1,-0.352692,-0.029848,-0.166482,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
2,0.039641,0.098849,1.180807,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
3,-0.502774,0.418877,-0.593671,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
4,-0.311909,-0.673335,-0.955139,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
5,-0.538459,0.794673,0.260707,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,2.986456
6,-0.526020,-0.673335,-1.267316,0.270603,0.479180,2.308156,-0.437674,-0.349749,-2.059820,-1.318638,1.470984,-0.785328,1.835497,-0.334845
7,-0.188540,-0.673335,0.178555,0.270603,-2.265952,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
8,1.800044,-0.673335,2.363793,-1.588932,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
9,-0.490539,0.356244,-0.215773,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,1.835497,-0.334845
10,-0.349634,-0.673335,-0.757975,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
11,-0.534381,-0.022984,0.425011,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
12,-0.130424,-0.673335,-1.579493,-2.518700,0.000000,-0.433246,-0.437674,2.859196,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
13,1.502328,-0.673335,0.490732,0.270603,-2.265952,-0.433246,2.284806,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
14,-0.028467,-0.673335,-0.199343,0.270603,0.479180,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
15,0.175653,-0.673335,-0.084330,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
16,-0.045391,0.577603,1.049364,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
17,-0.207912,-0.530481,-0.166482,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
18,0.901388,2.722560,2.692400,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
19,-0.714846,0.815265,-0.593671,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
20,-0.594944,0.021631,-1.448050,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,-0.334845
21,-0.555180,-0.673335,-1.776657,-2.518700,0.479180,-0.433246,-0.437674,2.859196,-2.059820,-1.318638,-0.679817,1.273353,1.835497,-0.334845
22,-0.182831,-0.673335,-0.577241,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
23,-0.212194,-0.673335,-0.182913,0.270603,0.479180,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,-0.679817,1.273353,1.835497,-0.334845
24,0.121208,1.205647,2.528096,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
25,-0.979937,9.622455,0.194986,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
26,-0.090253,-0.137096,0.063543,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
27,0.549430,0.935382,2.281641,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
28,-0.210767,-0.315985,-1.300177,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
29,-0.380017,0.348522,-0.182913,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,-0.512562,-0.004967,-0.281495,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
338,-0.498696,0.765931,-0.807266,-1.588932,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,2.986456
339,-0.096370,0.327502,0.425011,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,-2.059820,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
340,-0.445066,1.399122,-0.232204,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,2.986456
341,-0.169984,1.160603,0.835770,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,2.986456
342,-0.261746,-0.673335,-0.905848,-2.518700,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
343,-0.021533,-0.673335,-0.922279,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
344,0.418516,-0.673335,0.655036,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
345,0.719496,-0.673335,2.035186,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
346,-0.288459,0.170062,-0.051470,0.270603,-2.265952,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
347,-0.395107,-0.673335,-1.086582,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,1.835497,-0.334845
348,-0.282953,-0.081327,-0.018609,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,1.273353,1.835497,-0.334845
349,-0.470148,-0.546354,0.014252,-0.659165,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,2.986456
350,0.787400,-0.673335,1.936604,0.270603,0.479180,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
351,-0.514397,5.761534,-0.495089,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,-0.334845
352,0.206240,-0.282953,-0.445798,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
353,0.063907,0.943533,-0.265064,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
354,0.104079,-0.593114,0.359289,-2.518700,-2.265952,-0.433246,-0.437674,2.859196,0.485479,0.758358,1.470984,-0.785328,1.835497,-0.334845
355,0.570434,-0.152969,1.000073,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
356,-0.206893,0.157192,-0.840127,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
357,-0.470148,-0.673335,-1.250886,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,1.273353,-0.544812,-0.334845
358,-0.341273,-0.673335,-0.988000,0.270603,0.000000,-0.433246,2.284806,-0.349749,0.485479,0.758358,-0.679817,-0.785328,1.835497,-0.334845
359,-0.164274,0.470785,0.260707,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
360,0.763542,1.152023,-0.659393,0.270603,0.000000,-0.433246,-0.437674,-0.349749,-2.059820,0.758358,-0.679817,1.273353,-0.544812,-0.334845
361,-0.517252,0.256289,-0.610102,0.270603,0.479180,2.308156,-0.437674,-0.349749,0.485479,0.758358,1.470984,-0.785328,-0.544812,-0.334845
362,-0.162439,0.088982,-0.380077,0.270603,0.479180,-0.433246,-0.437674,2.859196,0.485479,0.758358,-0.679817,1.273353,1.835497,2.986456
363,-0.132056,-0.369180,-0.347216,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,1.273353,-0.544812,-0.334845
364,-0.317211,0.181644,-0.166482,0.270603,0.000000,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,1.470984,-0.785328,-0.544812,-0.334845
365,0.039641,0.353241,0.359289,0.270603,0.479180,-0.433246,-0.437674,-0.349749,0.485479,0.758358,-0.679817,-0.785328,-0.544812,-0.334845
366,0.896087,-0.673335,-0.626532,-2.518700,0.479180,-0.433246,-0.437674,-0.349749,0.485479,-1.318638,-0.679817,-0.785328,-0.544812,2.986456

In [102]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [103]:
y_pred = logmodel.predict(x_new)

In [104]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0], dtype=uint8)

In [105]:
len(y_pred)

367

In [106]:
len(y_test)

367

In [107]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 51,  26],
       [159, 131]], dtype=int64)

In [108]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=5, 
                                      metric='minkowski', p=2)

In [109]:
classifier_knn.fit(x_train, y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [110]:
y_pred = classifier_knn.predict(x_test)

In [111]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8)

In [112]:
confusion_matrix(y_test, y_pred)

array([[ 77,   0],
       [290,   0]], dtype=int64)

In [113]:
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(x_train, y_train)
y_pred=classifier_nb.predict(x_test)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [114]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0], dtype=uint8)

In [115]:
confusion_matrix(y_test, y_pred)

array([[ 42,  35],
       [164, 126]], dtype=int64)

In [142]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='sigmoid')
classifier_svm.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [143]:
y_pred = classifier_svm.predict(x_test)

In [144]:
y_pred

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0], dtype=uint8)

In [145]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 22,  55],
       [ 90, 200]], dtype=int64)

In [120]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='linear')
classifier_svm.fit(x_train,y_train)

y_pred = classifier_svm.predict(x_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[ 61,  16],
       [205,  85]], dtype=int64)

In [121]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='rbf')
classifier_svm.fit(x_train,y_train)

y_pred = classifier_svm.predict(x_test)

from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\DELL\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)

array([[  0,  77],
       [  0, 290]], dtype=int64)

In [125]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion='entropy')
classifier_dt.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [126]:
y_pred = classifier_dt.predict(x_test)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 55,  22],
       [196,  94]], dtype=int64)

In [127]:
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators=3, criterion='entropy')
classifier_rf.fit(x_train,y_train)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=3, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [128]:
y_pred = classifier_rf.predict(x_test)

In [129]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 50,  27],
       [128, 162]], dtype=int64)

In [130]:
dataset_New_Pred

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.000000,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.000000,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.000000,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,0.825444,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.000000,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.000000,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.000000,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.000000,Rural
8,LP001059,Male,Yes,2,Graduate,No,13633,0,280.0,240.0,1.000000,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.000000,Semiurban
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.000000,Urban
11,LP001082,Male,Yes,1,Graduate,No,2185,1516,162.0,360.0,1.000000,Semiurban
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,0.825444,Urban
13,LP001094,Male,Yes,2,Graduate,No,12173,0,166.0,360.0,0.000000,Semiurban
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.000000,Semiurban
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.000000,Urban
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.000000,Urban
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.000000,Semiurban
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.000000,Urban
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.000000,Semiurban
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.000000,Urban
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.000000,Urban
22,LP001128,Male,No,0,Graduate,No,3909,0,101.0,360.0,1.000000,Urban
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.000000,Urban
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.000000,Urban
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.000000,Rural
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,0.825444,Urban
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.000000,Urban
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,0.825444,Semiurban
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.000000,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.000000,Urban
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.000000,Rural
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.000000,Rural
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.000000,Semiurban
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.000000,Rural
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.000000,Rural
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.000000,Urban
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.000000,Rural
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.000000,Urban
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.000000,Rural
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.000000,Urban
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.000000,Urban
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.000000,Rural
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.000000,Rural
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,0.825444,Rural
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.000000,Urban
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.000000,Rural
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.000000,Semiurban
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.000000,Urban
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.000000,Urban
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.000000,Urban
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,0.825444,Rural
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.000000,Semiurban
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,0.825444,Urban
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.000000,Semiurban
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.000000,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.000000,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,0.825444,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.000000,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.000000,Rural

In [146]:
y_outcomes = pd.DataFrame(y_pred)

In [148]:
y_outcomes = y_outcomes.rename(columns={0:"outcomes"})

In [149]:
y_outcomes

     outcomes
0           0
1           1
2           1
3           0
4           1
5           1
6           1
7           1
8           1
9           0
10          1
11          0
12          1
13          1
14          0
15          0
16          1
17          1
18          1
19          0
20          1
21          1
22          1
23          1
24          1
25          1
26          1
27          1
28          1
29          1
..        ...
337         1
338         1
339         1
340         1
341         1
342         1
343         0
344         0
345         1
346         0
347         1
348         1
349         1
350         1
351         1
352         0
353         1
354         0
355         0
356         0
357         1
358         1
359         1
360         1
361         0
362         0
363         1
364         0
365         1
366         0

[367 rows x 1 columns]

In [150]:
y_outcomes[1] = y_outcomes['outcomes'].map( {1:'Y', 0:'N'} )

In [151]:
y_outcomes = y_outcomes.drop(['outcomes'], axis=1)

In [152]:
y_outcomes = y_outcomes.rename(columns={1:"outcomes"})

In [153]:
dataset_New_Pred

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.000000,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.000000,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.000000,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,0.825444,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.000000,Urban
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.000000,Urban
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.000000,Semiurban
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.000000,Rural
8,LP001059,Male,Yes,2,Graduate,No,13633,0,280.0,240.0,1.000000,Urban
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.000000,Semiurban
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.000000,Urban
11,LP001082,Male,Yes,1,Graduate,No,2185,1516,162.0,360.0,1.000000,Semiurban
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,0.825444,Urban
13,LP001094,Male,Yes,2,Graduate,No,12173,0,166.0,360.0,0.000000,Semiurban
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.000000,Semiurban
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.000000,Urban
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.000000,Urban
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.000000,Semiurban
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.000000,Urban
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.000000,Semiurban
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.000000,Urban
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.000000,Urban
22,LP001128,Male,No,0,Graduate,No,3909,0,101.0,360.0,1.000000,Urban
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.000000,Urban
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.000000,Urban
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.000000,Rural
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,0.825444,Urban
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.000000,Urban
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,0.825444,Semiurban
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.000000,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.000000,Urban
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.000000,Rural
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.000000,Rural
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.000000,Semiurban
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.000000,Rural
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.000000,Rural
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.000000,Urban
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.000000,Rural
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.000000,Urban
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.000000,Rural
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.000000,Urban
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.000000,Urban
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.000000,Rural
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.000000,Rural
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,0.825444,Rural
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.000000,Urban
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.000000,Rural
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.000000,Semiurban
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.000000,Urban
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.000000,Urban
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.000000,Urban
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,0.825444,Rural
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.000000,Semiurban
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,0.825444,Urban
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.000000,Semiurban
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.000000,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.000000,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,0.825444,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.000000,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.000000,Rural

In [154]:
dataset_new = pd.concat([dataset_New_Pred,y_outcomes], axis=1)

In [155]:
dataset_new

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,outcomes
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.000000,Urban,N
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.000000,Urban,Y
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.000000,Urban,Y
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,0.825444,Urban,N
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.000000,Urban,Y
5,LP001054,Male,Yes,0,Not Graduate,Yes,2165,3422,152.0,360.0,1.000000,Urban,Y
6,LP001055,Female,No,1,Not Graduate,No,2226,0,59.0,360.0,1.000000,Semiurban,Y
7,LP001056,Male,Yes,2,Not Graduate,No,3881,0,147.0,360.0,0.000000,Rural,Y
8,LP001059,Male,Yes,2,Graduate,No,13633,0,280.0,240.0,1.000000,Urban,Y
9,LP001067,Male,No,0,Not Graduate,No,2400,2400,123.0,360.0,1.000000,Semiurban,N
10,LP001078,Male,No,0,Not Graduate,No,3091,0,90.0,360.0,1.000000,Urban,Y
11,LP001082,Male,Yes,1,Graduate,No,2185,1516,162.0,360.0,1.000000,Semiurban,N
12,LP001083,Male,No,3+,Graduate,No,4166,0,40.0,180.0,0.825444,Urban,Y
13,LP001094,Male,Yes,2,Graduate,No,12173,0,166.0,360.0,0.000000,Semiurban,Y
14,LP001096,Female,No,0,Graduate,No,4666,0,124.0,360.0,1.000000,Semiurban,N
15,LP001099,Male,No,1,Graduate,No,5667,0,131.0,360.0,1.000000,Urban,N
16,LP001105,Male,Yes,2,Graduate,No,4583,2916,200.0,360.0,1.000000,Urban,Y
17,LP001107,Male,Yes,3+,Graduate,No,3786,333,126.0,360.0,1.000000,Semiurban,Y
18,LP001108,Male,Yes,0,Graduate,No,9226,7916,300.0,360.0,1.000000,Urban,Y
19,LP001115,Male,No,0,Graduate,No,1300,3470,100.0,180.0,1.000000,Semiurban,N
20,LP001121,Male,Yes,1,Not Graduate,No,1888,1620,48.0,360.0,1.000000,Urban,Y
21,LP001124,Female,No,3+,Not Graduate,No,2083,0,28.0,180.0,1.000000,Urban,Y
22,LP001128,Male,No,0,Graduate,No,3909,0,101.0,360.0,1.000000,Urban,Y
23,LP001135,Female,No,0,Not Graduate,No,3765,0,125.0,360.0,1.000000,Urban,Y
24,LP001149,Male,Yes,0,Graduate,No,5400,4380,290.0,360.0,1.000000,Urban,Y
25,LP001153,Male,No,0,Graduate,No,0,24000,148.0,360.0,0.000000,Rural,Y
26,LP001163,Male,Yes,2,Graduate,No,4363,1250,140.0,360.0,0.825444,Urban,Y
27,LP001169,Male,Yes,0,Graduate,No,7500,3750,275.0,360.0,1.000000,Urban,Y
28,LP001174,Male,Yes,0,Graduate,No,3772,833,57.0,360.0,0.825444,Semiurban,Y
29,LP001176,Male,No,0,Graduate,No,2942,2382,125.0,180.0,1.000000,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,LP002856,Male,Yes,0,Graduate,No,2292,1558,119.0,360.0,1.000000,Urban,Y
338,LP002857,Male,Yes,1,Graduate,Yes,2360,3355,87.0,240.0,1.000000,Rural,Y
339,LP002858,Female,No,0,Graduate,No,4333,2333,162.0,360.0,0.000000,Rural,Y
340,LP002860,Male,Yes,0,Graduate,Yes,2623,4831,122.0,180.0,1.000000,Semiurban,Y
341,LP002867,Male,No,0,Graduate,Yes,3972,4275,187.0,360.0,1.000000,Rural,Y
342,LP002869,Male,Yes,3+,Not Graduate,No,3522,0,81.0,180.0,1.000000,Rural,Y
343,LP002870,Male,Yes,1,Graduate,No,4700,0,80.0,360.0,1.000000,Urban,N
344,LP002876,Male,No,0,Graduate,No,6858,0,176.0,360.0,1.000000,Rural,N
345,LP002878,Male,Yes,3+,Graduate,No,8334,0,260.0,360.0,1.000000,Urban,Y
346,LP002879,Male,Yes,0,Graduate,No,3391,1966,133.0,360.0,0.000000,Rural,N
347,LP002885,Male,No,0,Not Graduate,No,2868,0,70.0,360.0,1.000000,Urban,Y
348,LP002890,Male,Yes,2,Not Graduate,No,3418,1380,135.0,360.0,1.000000,Urban,Y
349,LP002891,Male,Yes,0,Graduate,Yes,2500,296,137.0,300.0,1.000000,Rural,Y
350,LP002899,Male,Yes,2,Graduate,No,8667,0,254.0,360.0,1.000000,Rural,Y
351,LP002901,Male,No,0,Graduate,No,2283,15000,106.0,360.0,0.825444,Rural,Y
352,LP002907,Male,Yes,0,Graduate,No,5817,910,109.0,360.0,1.000000,Urban,N
353,LP002920,Male,Yes,0,Graduate,No,5119,3769,120.0,360.0,1.000000,Rural,Y
354,LP002921,Male,Yes,3+,Not Graduate,No,5316,187,158.0,180.0,0.000000,Semiurban,N
355,LP002932,Male,Yes,3+,Graduate,No,7603,1213,197.0,360.0,1.000000,Urban,N
356,LP002935,Male,Yes,1,Graduate,No,3791,1936,85.0,360.0,1.000000,Urban,N
357,LP002952,Male,No,0,Graduate,No,2500,0,60.0,360.0,1.000000,Urban,Y
358,LP002954,Male,Yes,2,Not Graduate,No,3132,0,76.0,360.0,0.825444,Rural,Y
359,LP002962,Male,No,0,Graduate,No,4000,2667,152.0,360.0,1.000000,Semiurban,Y
360,LP002965,Female,Yes,0,Graduate,No,8550,4255,96.0,360.0,0.825444,Urban,Y
361,LP002969,Male,Yes,1,Graduate,No,2269,2167,99.0,360.0,1.000000,Semiurban,N
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.000000,Urban,N
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.000000,Urban,Y
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,0.825444,Semiurban,N
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.000000,Rural,Y
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.000000,Rural,N

In [156]:
dataset_new.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
outcomes             0
dtype: int64

In [157]:
dataset_new.to_csv('Pred_DataSet_output.csv')